version: '3'

services:
    
    clientesdb:
        image: postgres:11.0-alpine
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - ../volumes/clientesdb:/var/lib/postgresql/data
    
    pedidosdb:
        image: postgres:11.0-alpine
        env_file:
            - .env
    
    pedidosrest:
        image: coticeadifrn/pedidosrest:1.0
        build:
            context: ../dockers/pedidosrest
        env_file:
            - .env
        volumes:
            - ../apps/pedidosrest:/apps/app


# docker-compose up
# docker ps -a
# docker run -e POSTGRES_USER=eu postgres:11.0-alpine 