version: '3'

services:
    
    clientesdb:
        image: postgres:11.0-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=eu
            - POSTGRES_PASSWORD=tu
        volumes:
            - ../volumes/clientesdb:/var/lib/postgresql/data
    
    pedidosdb:
        image: postgres:11.0-alpine
        environment:
            - POSTGRES_USER=eu
            - POSTGRES_PASSWORD=tu


# docker-compose up
# docker ps -a
# docker run -e POSTGRES_USER=eu postgres:11.0-alpine 