version: '3'

services:

    proxy:
        image: nginx:1.15.6-alpine
        ports:
            - "80:80"
        volumes:
            - "../dockers/proxy:/etc/nginx/conf.d"
        depends_on:
            # - pedidosrest
            - clientesrest
            # - pedidosui
            - clientesui

    clientesdb:
        image: postgres:11.0-alpine
        env_file:
            - .env
    
    pedidosdb:
        image: postgres:11.0-alpine
        env_file:
            - .env
    
    pedidosrest:
        image: coticeadifrn/pedidosrest:1.0
        build:
            context: ../dockers/pedidosrest
        env_file:
            - .env
        volumes:
            - ../apps/pedidosrest:/apps/app
    
    clientesui:
        image: coticeadifrn/vue:1.0
        ports:
            - 8080:8080
        build:
            context: ../dockers/clientesui
        env_file:
            - .env
        volumes:
            - ../apps/clientesui:/apps/app

    pedidosui:
        image: coticeadifrn/pedidosui:1.0
        ports:
            - 3000:3000
        build:
            context: ../dockers/pedidosui
        env_file:
            - .env
        volumes:
            - ../apps/pedidosui:/apps/app   
            
    clientesrest:
        image: coticeadifrn/clientesrest:1.0
        ports:
            - 9000:9000
        build:
            context: ../dockers/clientesrest
        env_file:
            - .env
        volumes:
            - ../apps/clientesrest:/apps/app
        depends_on:
            - clientesdb


# docker-compose up
# docker ps -a
# docker run -e POSTGRES_USER=eu postgres:11.0-alpine 